blog/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', PostListView.as_view(), name='blog'),


]

books_magazine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import  handler404

from library.views import error_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('basket/', include('basket.urls')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error_404

library/urls.py
from django.urls import path
from rest_framework import routers
from django.urls import include
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

from library.views import index_all, index_books, book_detail, BookCreateView, supplier_form, SupplierCreateView, \
    BookListView, BookDetailView, user_registration, user_login, BookAdminListView, BookUpdateView, SupplireListView, \
    SupplireUpdateView, SupplierDeleteView, BookDeleteView, user_logout, send_contact_email, AuthorListView, \
    AuthorDetailView, AuthorAdminListView, book_api_list, BookViewSet, AuthorViewSet, AuthorCreateView, \
    AuthorUpdateView, AuthorDeleteView, FilterBooksView, BookListFilterView

router = routers.SimpleRouter()
router.register('book_class', BookViewSet)
router.register('author_class', AuthorViewSet)

urlpatterns = [
        path('index/book/<int:book_id>', book_detail, name='book_detail'),
    path('index/books/booksform', BookCreateView.as_view(), name='book_form'),
    path('', BookListView.as_view(), name='index'),
    path('index/books/filter', FilterBooksView.as_view(), name='book_filter'),
    path('index/books/supp', supplier_form, name='supplier_form'),
    path('index/books/supplierform', SupplierCreateView.as_view(), name='supplier_form_class'),
    path('index/books/<int:book_id>', BookDetailView.as_view(), name='book_detail'),
    path('index/account/registration/', user_registration, name='registration'),
    path('index/account/auth/', user_login, name='auth'),
    path('index/account/books_admin/', BookAdminListView.as_view(), name='books_admin'),
    path('index/account/book_updete/<int:pk>', BookUpdateView.as_view(), name='books_update'),
    path('index/supplire/supplire_admin/', SupplireListView.as_view(), name='supplire_admin'),
    path('index/supplire/supplire_update/<int:pk>', SupplireUpdateView.as_view(), name='supplire_update'),
    path('index/supplire/supplire_delete/<int:pk>', SupplierDeleteView.as_view(), name='supplire_delete'),
    path('index/account/book_delete/<int:pk>', BookDeleteView.as_view(), name='book_delete'),
    path('index/account/logout/', user_logout, name='logout'),
    path('index/contact/', send_contact_email, name='contact'),
    path('index/authors/', AuthorListView.as_view(), name='authors'),
    path('index/authors/author_detail/<int:author_id>', AuthorDetailView.as_view(), name='author_detail'),
    path('index/authors/author_admin/', AuthorAdminListView.as_view(), name='author_admin'),
    path('index/authors/author_create/', AuthorCreateView.as_view(), name='author_create'),
    path('index/supplire/author_update/<int:pk>', AuthorUpdateView.as_view(), name='author_update'),
    path('index/supplire/author_delete/<int:pk>', AuthorDeleteView.as_view(), name='author_delete'),
    path('api/books/', book_api_list, name='api_books'),
    path('api/', include(router.urls)),
    path('api/', include(router.urls)),
    path('index/books/', BookListFilterView.as_view(), name='book_list'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

library/models.py
from django.db import models
from django.urls import reverse, reverse_lazy
# Create your models here.


# class Status_Book(models.Model):
#     status_book = models.CharField(max_length=10, verbose_name='Статус', choices=[('1', 'BESTSELLER'), ('2', 'HOT'), ('3', 'NEW'), ('4', 'SALE')], default='3')
#
#     def __str__(self):  # Переопределение названия объекта
#         return self.status_book
#
#     class Meta:  # Класс для названий нашей модели в админке
#         verbose_name = 'Статус'  # Надпись в единственном числе
#         verbose_name_plural = 'Статусы'  # Надпись во множественном числе
#         ordering = ['status_book']  # Сортировка полей (по возрастанию)


class Genre(models.Model):
    genre = models.CharField(max_length=120, verbose_name='Жанр')

    def __str__(self):  # Переопределение названия объекта
        return self.genre

    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Жанр'  # Надпись в единственном числе
        verbose_name_plural = 'Жанры'  # Надпись во множественном числе
        ordering = ['genre']  # Сортировка полей (по возрастанию)


class Author(models.Model):
    author_firstname = models.CharField(max_length=100, verbose_name='Фамилия автора')
    author_name = models.CharField(max_length=100, verbose_name='Имя автора')
    author_patronymic = models.CharField(max_length=100, null=True, blank=True, verbose_name='Отчетсво автора')
    biography = models.TextField(blank=True, null=True, verbose_name='Биография')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True, verbose_name='Фотография')
    date_of_birth = models.DateField(verbose_name='День рождения')
    date_of_death = models.DateField(null=True, blank=True, verbose_name='День смерти', default=None)

    def __str__(self):  # Переопределение названия объекта
        return f"{self.author_firstname}  {self.author_name}  {self.author_patronymic}"

    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Автор'  # Надпись в единственном числе
        verbose_name_plural = 'Авторы'  # Надпись во множественном числе
        ordering = ['author_firstname']  # Сортировка полей (по возрастанию)

    # def __str__(self):
    #     if self.date_of_death == None:
    #         return f'{self.date_of_death = 'Жив по сей день'}'


class book(models.Model):
    name = models.CharField(max_length=120, default='Книга', verbose_name='Название')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    pages = models.FloatField(default=10, verbose_name='Количество страниц')
    price = models.FloatField(default=10, verbose_name='Цена')
    cover_type = models.CharField(max_length=120, verbose_name='Тип обложки')
    size = models.CharField(max_length=100, verbose_name='Размер')
    date_publication = models.DateField(null=True, verbose_name='Дата публикации')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True, verbose_name='Фотография')
    date_update = models.DateField(auto_now=True, null=True, verbose_name='Дата изменения записи')
    exist = models.BooleanField(default=True, verbose_name='В каталоге?')

    supplier = models.ForeignKey('Supplier', on_delete=models.PROTECT, null=True, verbose_name='Поставщик')
    authors = models.ManyToManyField(Author, verbose_name='Автор')
    genres = models.ManyToManyField(Genre, verbose_name='Жанр')
    # status_book = models.ForeignKey(Status_Book, on_delete=models.PROTECT, null=True, verbose_name='Статус книги')
    status_book = models.CharField(max_length=10, verbose_name='Статус',
                                   choices=[('BESTSELLER', 'BESTSELLER'), ('HOT', 'HOT'), ('NEW', 'NEW'), ('SALE', 'SALE')],
                                   default='NEW')

    def get_absolute_url(self):  # тэг url для объекта (Данный метод для вывода странички одной записи)
        return reverse('book_detail', kwargs={'book_id': self.pk})


    def __str__(self):  # Переопределение названия объекта
        return self.name

    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Книга'  # Надпись в единственном числе
        verbose_name_plural = 'Книги'  # Надпись во множественном числе
        ordering = ['name']  # Сортировка полей (по возрастанию)


class Supplier(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название компании поставщика')
    agent_firstname = models.CharField(max_length=100, verbose_name='Фамилия агента поставщика')
    agent_name = models.CharField(max_length=100, verbose_name='Имя агента поставщика')
    agent_patronymic = models.CharField(max_length=100, verbose_name='Отчетсво агента поставщика')
    exist = models.BooleanField(default=True, verbose_name='Сотрудничаем?')

    def __str__(self):
        return self.title

    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Поставщик'  # Надпись в единственном числе
        verbose_name_plural = 'Поставщики'  # Надпись во множественном числе
        ordering = ['title']  # Сортировка полей (по возрастанию)


class Order(models.Model):
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    date_finish = models.DateTimeField(null=True, verbose_name='Дата завершения заказа')
    price = models.FloatField(null=True, verbose_name='Стоимость заказа')
    address_delivery = models.CharField(max_length=150, verbose_name='Адрес доставки')
    status = models.CharField(max_length=150, verbose_name='Статус', choices=[('1', 'Создан'),
                                                                              ('2', 'Отменён'),
                                                                              ('3', 'Согласован'),
                                                                              ('4', 'В пути'),
                                                                              ('5', 'Завершен')])

    books = models.ManyToManyField(book, through='Pos_order')

    def __str__(self):
        return f"{self.date_create} | {self.status} | {self.price}"

    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Заказ'  # Надпись в единственном числе
        verbose_name_plural = 'Заказы'  # Надпись во множественном числе
        ordering = ['date_create']  # Сортировка полей (по возрастанию)

class Pos_order(models.Model):
    book = models.ForeignKey(book, on_delete=models.PROTECT, verbose_name='Книга')
    order = models.ForeignKey(Order, on_delete=models.PROTECT, verbose_name='Заказ')
    count_book = models.IntegerField(verbose_name='Количество книг')
    price = models.IntegerField(verbose_name='Общая цена книг')

    def __str__(self):
        return self.book.name + " " + self.order.address_delivery + " " + self.order.status


    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Позиция'  # Надпись в единственном числе
        verbose_name_plural = 'Позиции'  # Надпись во множественном числе
        ordering = ['book', 'order', 'price']  # Сортировка полей (по возрастанию)


class Cheque(models.Model):
    date_print = models.DateTimeField(auto_now_add=True, verbose_name='Дата распечатки')
    address_print = models.CharField(max_length=150, verbose_name='Место создание чека')
    terminal = models.CharField(max_length=10, verbose_name='Код терминала')

    order = models.OneToOneField(Order, on_delete=models.PROTECT, primary_key=True)


    def __str__(self):
        return str(self.date_print) + " " + self.terminal


    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Чек'  # Надпись в единственном числе
        verbose_name_plural = 'Чеки'  # Надпись во множественном числе
        ordering = ['terminal', 'date_print']  # Сортировка полей (по возрастанию)

library/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms import HiddenInput

from library.models import book, Supplier, Author


class BookForm(forms.ModelForm):
    class Meta:
        model = book
        fields = ['name', 'description', 'pages', 'price', 'cover_type', 'size', 'date_publication', 'photo', 'supplier']

        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'input_box',
                }
            ),
            'description': forms.TextInput(
                attrs={
                    'class': 'input_box',
                }
            ),
            'pages': forms.NumberInput(
                attrs={
                    'class': 'input_box',
                }
            ),
            'price': forms.NumberInput(
                attrs={
                    'class': 'input_box',
                }
            ),
            'cover_type': forms.TextInput(
                attrs={
                    'class': 'input_box',
                }
            ),
            'size': forms.TextInput(
                attrs={
                    'class': 'input_box',
                }
            ),
            'date_publication': forms.DateInput(
                attrs={
                    'class': 'input_box',
                }
            ),
            'photo': forms.FileInput(
                attrs={
                    'class': 'input_box',
                }
            ),
            'supplier': forms.Select(
                attrs={
                    'class': 'input_box',
                }
            ),
        }

    # Валидация
    # required=True - обязательное поле
    # max_length - максимальная длина текста
    # min_length - минимальная длина текста
    # max_value - максимальное значение числа
    # max_value - минимальное значение числа
    # step_size - шаг при установки числового значения

    # Стили
    # label - Вывод названия
    # widget - Указания типа поля
    # initial - Значение по умолчанию
    # help_text - подсказка под полем


class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ['title', 'agent_firstname', 'agent_name', 'agent_patronymic', 'exist']


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Логин'
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput
    )


class EditForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def pas(self):
        for field_name, field in self.fields.items():
            if field_name == 'password':
                field.widget = HiddenInput()

# email
class ContactForm(forms.Form):
    # recipient = forms.EmailField(
    #     label='Получатель',
    #     required=False,
    #     widget=forms.EmailInput(
    #         attrs={'class': 'form-control'}
    #     )
    # )
    subject = forms.CharField(
        label='Тема письма',
        widget=forms.TextInput(
            attrs={'class':'form-control'}
        )
    )
    content = forms.CharField(
        label='Тело письма',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 8
            }
        )
    )


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['author_firstname', 'author_name', 'author_patronymic', 'biography', 'photo', 'date_of_birth', 'date_of_death']
        #
        # widgets = {
        #     'author_firstname': forms.TextInput(
        #         attrs={
        #             'class': 'input_box',
        #         }
        #     ),
        #     'author_name': forms.TextInput(
        #         attrs={
        #             'class': 'input_box',
        #         }
        #     ),
        #     'author_patronymic': forms.TextInput(
        #         attrs={
        #             'class': 'input_box',
        #         }
        #     ),
        #     'biography': forms.TextInput(
        #         attrs={
        #             'class': 'input_box',
        #         }
        #     ),
        #
        #     'photo': forms.FileInput(
        #         attrs={
        #             'class': 'input_box',
        #         }
        #     ),
        #     'date_of_birth': forms.DateInput(
        #         attrs={
        #             'class': 'input_box',
        #         }
        #     ),
        #     'date_of_death': forms.DateInput(
        #         attrs={
        #             'class': 'input_box',
        #         }
        #     )
        # }

library/templates/library/account.html
	{% extends 'base.html' %}
	{% load static %}
	{% block content %}
	{% include 'inc/_header_account.html' %}

<!-- Start My Account Area -->
<section class="my_account_area pt--80 pb--55 bg--white">
	<div class="container">

			<div class="col-lg-6 col-12">
				<div class="my__account__wrapper">
					<h3 class="account__title">Register</h3>
					<form  method="post">
                    {% csrf_token %}
						<div class="account__form">
                            {% for field in form %}
							<div class="input__box" >
								<label for="{{ field.id_for_label }}">{{ field.label }} <span>*</span></label>
								{{ field }}
							</div>
                            {% endfor %}
							<div class="form__btn">
								<button>Register</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
<div>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert-info"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
</div>

</section>
<!-- End My Account Area -->

	{% include 'inc/_footer.html' %}

	{% endblock %}

library/templates/library/auth.html
	{% extends 'base.html' %}
	{% load static %}
	{% block content %}
	{% include 'inc/_header_account.html' %}

<!-- Start My Account Area -->
<section class="my_account_area pt--80 pb--55 bg--white">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-12">
				<div class="my__account__wrapper">
					<h3 class="account__title">Login</h3>
					<form  method="post">
                    {% csrf_token %}
						<div class="account__form">
                            {% for field in form_l %}
							<div class="input__box" >
								<label for="{{ field.id_for_label }}">{{ field.label }} <span>*</span></label>
								{{ field }}
							</div>
                            {% endfor %}
                            <div class="form__btn">
								<button>Login</button>

						</div>
					</form>
				</div>
			</div>
        </div>
	</div>
    <div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="alert alert-info"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    </div>

</section>
<!-- End My Account Area -->

	{% include 'inc/_footer.html' %}

	{% endblock %}

library/templates/library/author.html
	{% extends 'base.html' %}
	{% load static %}
	{% block content %}
	{% include 'inc/_header_account.html' %}

        <!-- Start Team Area -->
        <section class="wn__team__area pt--40 pb--75 bg--white">
        	<div class="container">
        		<div class="row">
                    {% for author in authors_list %}
                    <!-- Start Single Team -->
        			<div class="col-lg-3">
        				<div class="wn__team text-center">
        					<div class="thumb" >
                                <a href="{% url 'author_detail' author.pk %}">
        						<img src="{{ author.photo.url }}" alt="Team images"  height="300">
                                </a>
        					</div>
        					<div class="content">
        						<h4>{{ author.author_name }} {{ author.author_firstname }}</h4>
        						<p>Head</p>
        						<ul class="team__social__net">
        							<li><a href="#"><i class="icon-social-twitter icons"></i></a></li>
        							<li><a href="#"><i class="icon-social-tumblr icons"></i></a></li>
        							<li><a href="#"><i class="icon-social-facebook icons"></i></a></li>
        							<li><a href="#"><i class="icon-social-linkedin icons"></i></a></li>
        							<li><a href="#"><i class="icon-social-pinterest icons"></i></a></li>
        						</ul>
        					</div>
        				</div>
        			</div>
        			<!-- End Single Team -->
                    {% endfor %}


        		</div>
        	</div>
        </section>
        <!-- End Team Area -->

	{% include 'inc/_footer.html' %}

	{% endblock %}

library/templates/library/author_detail.html
{% extends 'base.html' %}
	{% load static %}
	{% block content %}
	{% include 'inc/_header_account.html' %}

<!-- Start main Content -->
<div class="maincontent bg--white pt--80 pb--55">
	<div class="container">
		<div class="row">
			<div class="col-lg-9 col-12">
				<div class="wn__single__product">
					<div class="row">
						<div class="col-lg-6 col-12">
							<div class="wn__fotorama__wrapper">
								<div class="fotorama wn__fotorama__action" data-nav="thumbs">
									<a><img src="{{ author_item.photo.url }}" alt=""></a>

								</div>
							</div>
						</div>
						<div class="col-lg-6 col-12">
							<div class="product__info__main">
								<h1>{{ author_item.author_name }} {{ author_item.author_firstname }}</h1>


								<div class="product__overview">

									<ul class="pro__attribute">
										<li>• Даты жизни: {{ author_item.date_of_birth }} {% if author_item.date_of_death == None %} {{ '- по настоящее время' }} {% else %} - {{ author_item.date_of_death }} {% endif %}</li>

									</ul>

								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="product__info__detailed">
					<div class="pro_details_nav nav justify-content-start" role="tablist">
						<a class="nav-item nav-link active" data-toggle="tab" href="#nav-details" role="tab">Биография</a>
						<a class="nav-item nav-link" data-toggle="tab" href="#nav-review" role="tab">Книги</a>
					</div>
					<div class="tab__container">
						<!-- Start Single Tab Content -->
						<div class="pro__tab_label tab-pane fade show active" id="nav-details" role="tabpanel">
							<div class="description__attribute">
								<p>{{ author_item.biography }}</p>
							</div>
						</div>
                        <!-- Start Single Tab Content -->
						<div class="pro__tab_label tab-pane fade" id="nav-review" role="tabpanel">
							<div class="review__attribute">
                                <h2>Список книг автора</h2>
                                {% for books in author_item.book_set.all %}
                                    <li> <a href="{% url 'book_detail' books.pk %}"> {{ books }} </a> </li>
                                {% endfor %}
							</div>
						</div>
						<!-- End Single Tab Content -->
					</div>
				</div>
		</div>
	</div>
</div>



	{% include 'inc/_footer.html' %}

	{% endblock %}

library/templates/library/author_form.html
	{% extends 'base.html' %}
	{% load static %}
	{% block content %}
	{% include 'inc/_header_forms.html' %}

<!-- Start Checkout Area -->

<section class="wn__checkout__area section-padding--lg bg__white">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="wn_checkout_wrap">
					<div class="checkout_info">
						<span>Автор</span>
						<a class="showlogin" href="#">Нажмите для ввода</a>
					</div>
					<div class="checkout_login">
						<form method="post" class="wn__checkout__form" enctype="multipart/form-data">
                            {% csrf_token %}
							<p>Новый автор</p>
                            {% for field in form %}
                                <div>
				                    <div>
					                    <label for="{{ field.id_for_label }}">{{ field.label }}<span>*</span></label>
				                    </div>
                                    {{ field }}
                                </div>
                                {{ field.errors }}
                            {% endfor %}
                            <br><br>

							<div class="form__btn">
								<button>Добавить</button>

                            </div>
						</form>
					</div>
</section>
<!-- End Checkout Area -->

	{% include 'inc/_footer.html' %}

	{% endblock %}

library/templates/library/author_update.html
	{% extends 'base.html' %}
	{% load static %}
	{% block content %}
	{% include 'inc/_header_forms.html' %}
<!-- Start Checkout Area -->

<section class="wn__checkout__area section-padding--lg bg__white">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="wn_checkout_wrap">
					<div class="checkout_info">
						<span>{{ object.title }}</span>
						<a class="showlogin" href="#">Нажмите для изменения данных</a>
                        <a class="form__btn" href="{% url 'author_admin' %}">Нажмите чтоб вернуться к списку</a>
					</div>
					<div class="checkout_login">
						<form method="post" class="wn__checkout__form" enctype="multipart/form-data">
                            {% csrf_token %}
							<p>Редактирование автора</p>
                            {% for field in form %}
                                <div>
				                    <div>
					                    <label for="{{ field.id_for_label }}">{{ field.label }}<span>*</span></label>
				                    </div>
                                    {{ field }}
                                </div>
                                {{ field.errors }}
                            {% endfor %}
                            <br>

							<div class="form__btn">
								<button>Изменить</button>
                            </div>
						</form>
					</div>
</section>


<!-- End Checkout Area -->

	{% include 'inc/_footer.html' %}

	{% endblock %}

library/templates/library/supplier_admin.html
	{% extends 'base.html' %}
	{% load static %}
	{% block content %}
	{% include 'inc/_header_account.html' %}

        <div class="wishlist-area section-padding--lg bg__white">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="wishlist-content">
                            <form action="#">
                                <div class="wishlist-table wnro__table table-responsive">
                                    <table>
                                        <thead>
                                            <tr>
                                                <th class="product-remove"></th>
                                                <th class="product-thumbnail"></th>
                                                <th class="product-name"><span class="nobr">Название</span></th>
                                                <th class="product-price"><span class="nobr"> ФИО Агента </span></th>
                                                <th class="product-stock-stauts"><span class="nobr"> Статус </span></th>
                                                <th class="product-add-to-cart"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for item in supplier_list %}
                                            <tr>
                                                <td class="product-remove"><a type="button" data-toggle="modal" data-target="#exampleModalLive{{ item.pk }}">Del</a></td>
                                                <td class="product-thumbnail"><a href="#"><img src="{% static 'css/images/product/sm-3/1.jpg' %}" alt=""></a></td>
                                                <td class="product-name"><a href="#">{{ item.title }}</a></td>
                                                <td class="product-price">{{item.agent_firstname}} {{item.agent_name}} {{item.agent_patronymic}}</td>
                                                <td class="product-stock-status"><span class="wishlist-in-stock">{{item.exist}}</span></td>
                                                <td class="product-add-to-cart"><a href="{% url 'supplire_update' item.pk %}">Редактирование</a></td>
                                            </tr>
                                             <!-- Модальное окно -->
                                                 <div id="exampleModalLive{{ item.pk }}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                            <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLiveLabel">Подтвердите удаление поставщика</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                            </div>
                                            <div class="modal-body">
                                            <p>При подтверждении поставщик удалится из базы данных без возможности востанавления!</p>
                                            </div>
                                            <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>

                                               <form method="post" action="{% url 'supplire_delete' item.pk %}">
                                                   {% csrf_token %}
                                            <button
                                                    type="submit" class="btn btn-danger">Удалить</button>
                                                   </form>

                                            </div>
                                            </div>
                                            </div>
                                            </div>
                                        {% endfor %}
                                        <tr>
                                                <td> </td>
                                                <td> </td>
                                                <td> </td>
                                                <td> </td>
                                                <td> </td>
                                                <td class="product-add-to-cart"><a href="{% url 'supplier_form_class' %}">Добавить поставщика</a></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>





	{% include 'inc/_footer.html' %}

	{% endblock %}