blog/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', PostListView.as_view(), name='blog'),


]

books_magazine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import  handler404

from library.views import error_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('basket/', include('basket.urls')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = error_404

library/models.py
from django.db import models
from django.urls import reverse, reverse_lazy
# Create your models here.


# class Status_Book(models.Model):
#     status_book = models.CharField(max_length=10, verbose_name='Статус', choices=[('1', 'BESTSELLER'), ('2', 'HOT'), ('3', 'NEW'), ('4', 'SALE')], default='3')
#
#     def __str__(self):  # Переопределение названия объекта
#         return self.status_book
#
#     class Meta:  # Класс для названий нашей модели в админке
#         verbose_name = 'Статус'  # Надпись в единственном числе
#         verbose_name_plural = 'Статусы'  # Надпись во множественном числе
#         ordering = ['status_book']  # Сортировка полей (по возрастанию)


class Genre(models.Model):
    genre = models.CharField(max_length=120, verbose_name='Жанр')

    def __str__(self):  # Переопределение названия объекта
        return self.genre

    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Жанр'  # Надпись в единственном числе
        verbose_name_plural = 'Жанры'  # Надпись во множественном числе
        ordering = ['genre']  # Сортировка полей (по возрастанию)


class Author(models.Model):
    author_firstname = models.CharField(max_length=100, verbose_name='Фамилия автора')
    author_name = models.CharField(max_length=100, verbose_name='Имя автора')
    author_patronymic = models.CharField(max_length=100, null=True, blank=True, verbose_name='Отчетсво автора')
    biography = models.TextField(blank=True, null=True, verbose_name='Биография')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True, verbose_name='Фотография')
    date_of_birth = models.DateField(verbose_name='День рождения')
    date_of_death = models.DateField(null=True, blank=True, verbose_name='День смерти', default=None)

    def __str__(self):  # Переопределение названия объекта
        return f"{self.author_firstname}  {self.author_name}  {self.author_patronymic}"

    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Автор'  # Надпись в единственном числе
        verbose_name_plural = 'Авторы'  # Надпись во множественном числе
        ordering = ['author_firstname']  # Сортировка полей (по возрастанию)

    # def __str__(self):
    #     if self.date_of_death == None:
    #         return f'{self.date_of_death = 'Жив по сей день'}'


class book(models.Model):
    name = models.CharField(max_length=120, default='Книга', verbose_name='Название')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    pages = models.FloatField(default=10, verbose_name='Количество страниц')
    price = models.FloatField(default=10, verbose_name='Цена')
    cover_type = models.CharField(max_length=120, verbose_name='Тип обложки')
    size = models.CharField(max_length=100, verbose_name='Размер')
    date_publication = models.DateField(null=True, verbose_name='Дата публикации')
    photo = models.ImageField(upload_to='image/%Y/%m/%d', null=True, verbose_name='Фотография')
    date_update = models.DateField(auto_now=True, null=True, verbose_name='Дата изменения записи')
    exist = models.BooleanField(default=True, verbose_name='В каталоге?')

    supplier = models.ForeignKey('Supplier', on_delete=models.PROTECT, null=True, verbose_name='Поставщик')
    authors = models.ManyToManyField(Author, verbose_name='Автор')
    genres = models.ManyToManyField(Genre, verbose_name='Жанр')
    # status_book = models.ForeignKey(Status_Book, on_delete=models.PROTECT, null=True, verbose_name='Статус книги')
    status_book = models.CharField(max_length=10, verbose_name='Статус',
                                   choices=[('BESTSELLER', 'BESTSELLER'), ('HOT', 'HOT'), ('NEW', 'NEW'), ('SALE', 'SALE')],
                                   default='NEW')

    def get_absolute_url(self):  # тэг url для объекта (Данный метод для вывода странички одной записи)
        return reverse('book_detail', kwargs={'book_id': self.pk})


    def __str__(self):  # Переопределение названия объекта
        return self.name

    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Книга'  # Надпись в единственном числе
        verbose_name_plural = 'Книги'  # Надпись во множественном числе
        ordering = ['name']  # Сортировка полей (по возрастанию)


class Supplier(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название компании поставщика')
    agent_firstname = models.CharField(max_length=100, verbose_name='Фамилия агента поставщика')
    agent_name = models.CharField(max_length=100, verbose_name='Имя агента поставщика')
    agent_patronymic = models.CharField(max_length=100, verbose_name='Отчетсво агента поставщика')
    exist = models.BooleanField(default=True, verbose_name='Сотрудничаем?')

    def __str__(self):
        return self.title

    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Поставщик'  # Надпись в единственном числе
        verbose_name_plural = 'Поставщики'  # Надпись во множественном числе
        ordering = ['title']  # Сортировка полей (по возрастанию)


class Order(models.Model):
    date_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    date_finish = models.DateTimeField(null=True, verbose_name='Дата завершения заказа')
    price = models.FloatField(null=True, verbose_name='Стоимость заказа')
    address_delivery = models.CharField(max_length=150, verbose_name='Адрес доставки')
    status = models.CharField(max_length=150, verbose_name='Статус', choices=[('1', 'Создан'),
                                                                              ('2', 'Отменён'),
                                                                              ('3', 'Согласован'),
                                                                              ('4', 'В пути'),
                                                                              ('5', 'Завершен')])

    books = models.ManyToManyField(book, through='Pos_order')

    def __str__(self):
        return f"{self.date_create} | {self.status} | {self.price}"

    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Заказ'  # Надпись в единственном числе
        verbose_name_plural = 'Заказы'  # Надпись во множественном числе
        ordering = ['date_create']  # Сортировка полей (по возрастанию)

class Pos_order(models.Model):
    book = models.ForeignKey(book, on_delete=models.PROTECT, verbose_name='Книга')
    order = models.ForeignKey(Order, on_delete=models.PROTECT, verbose_name='Заказ')
    count_book = models.IntegerField(verbose_name='Количество книг')
    price = models.IntegerField(verbose_name='Общая цена книг')

    def __str__(self):
        return self.book.name + " " + self.order.address_delivery + " " + self.order.status


    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Позиция'  # Надпись в единственном числе
        verbose_name_plural = 'Позиции'  # Надпись во множественном числе
        ordering = ['book', 'order', 'price']  # Сортировка полей (по возрастанию)


class Cheque(models.Model):
    date_print = models.DateTimeField(auto_now_add=True, verbose_name='Дата распечатки')
    address_print = models.CharField(max_length=150, verbose_name='Место создание чека')
    terminal = models.CharField(max_length=10, verbose_name='Код терминала')

    order = models.OneToOneField(Order, on_delete=models.PROTECT, primary_key=True)


    def __str__(self):
        return str(self.date_print) + " " + self.terminal


    class Meta:  # Класс для названий нашей модели в админке
        verbose_name = 'Чек'  # Надпись в единственном числе
        verbose_name_plural = 'Чеки'  # Надпись во множественном числе
        ordering = ['terminal', 'date_print']  # Сортировка полей (по возрастанию)

templates/inc/_footer.html
{% load static %}
		<!-- Footer Area -->
		<footer id="wn__footer" class="footer__area bg__cat--8 brown--color">
			<div class="footer-static-top">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<div class="footer__widget footer__menu">
								<div class="ft__logo">
									<a href="index.html">
										<img src="{% static 'css/images/logo/3.png' %}" alt="logo">
									</a>
									<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered duskam alteration variations of passages</p>
								</div>
								<div class="footer__content">
									<ul class="social__net social__net--2 d-flex justify-content-center">
										<li><a href="#"><i class="bi bi-facebook"></i></a></li>
										<li><a href="#"><i class="bi bi-google"></i></a></li>
										<li><a href="#"><i class="bi bi-twitter"></i></a></li>
										<li><a href="#"><i class="bi bi-linkedin"></i></a></li>
										<li><a href="#"><i class="bi bi-youtube"></i></a></li>
									</ul>
									<ul class="mainmenu d-flex justify-content-center">
										<li><a href="index.html">Trending</a></li>
										<li><a href="index.html">Best Seller</a></li>
										<li><a href="index.html">All Product</a></li>
										<li><a href="index.html">Wishlist</a></li>
										<li><a href="index.html">Blog</a></li>
										<li><a href="{% url 'contact' %}">Contact</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="copyright__wrapper">
				<div class="container">
					<div class="row">
						<div class="col-lg-6 col-md-6 col-sm-12">
							<div class="copyright">
								<div class="copy__right__inner text-left">
									<p>Copyright <i class="fa fa-copyright"></i> <a href="#">Boighor.</a> All Rights Reserved</p>
								</div>
							</div>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-12">
							<div class="payment text-right">
								<img src="{% static 'css/images/icons/payment.png' %}" alt="" />
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
		<!-- //Footer Area -->
		

templates/inc/_header.html
{% load static %}
		<!-- Header -->
		<header id="wn__header" class="header__area header__absolute sticky__header">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-6 col-sm-6 col-6 col-lg-2">
						<div class="logo">
							<a href="index.html">
								<img src="{% static 'css/images/logo/logo.png' %}" alt="logo images">
							</a>
						</div>
					</div>
					<div class="col-lg-8 d-none d-lg-block">
						<nav class="mainmenu__nav">
							<ul class="meninmenu d-flex justify-content-start">
								<li class="drop with--one--item"><a href="{% url 'book_list' %}">Книги</a></li>
								<li class="drop"><a href="{% url 'authors' %}">Авторы</a></li>
								<li><a href="{% url 'contact' %}">Контакты</a></li>
                                {% if user.is_authenticated and user.is_superuser  %}
                                <li><a href="{% url 'admin:index' %}">Админка</a></li>
                                {% endif %}
                                {% if user.is_authenticated %}
                                    {% if user.groups.all.0.name == 'Администратор' %}
                                <li class="drop"><a href="">Администрирование</a>
                                    <div class="megamenu mega03">
									<ul class="item item03">
										<li><a href="{% url 'supplire_admin' %}">Администрирование поставщиков</a></li>
										<li><a href="{% url 'books_admin' %}">Администрирование книг</a></li>
										<li><a href="{% url 'author_admin' %}">Администрирование авторов</a></li>
									</ul>
                                    </div>
								</li>
                                {% endif %}
                                {% endif %}
							</ul>
						</nav>
					</div>

					<div class="col-md-6 col-sm-6 col-6 col-lg-2">
						<ul class="header__sidebar__right d-flex justify-content-end align-items-center">
							<li class="shop_search"><a class="search__active" href="#"></a></li>
							<li class="wishlist"><a href="#"></a></li>
							<li class="shopcart"><a class="cartbox_active" href="#"><span class="product_qun">{{basket.total_price }}</span></a>
                            {% if user.is_authenticated %}
                            <li ><a href="#"><span>{% if user.first_name %}{{ user.last_name }} {{ user.first_name }}{% else %}Пользователь{% endif %}</span></a></li>
                            {% endif %}
<!-- Start Shopping Cart -->
						<div class="block-minicart minicart__active">
							<div class="minicart-content-wrapper">
								<div class="micart__close">
									<span>close</span>
								</div>

								<div class="mini_action checkout">
									<a class="checkout__btn" href="{% url 'list_basket_prod' %}">Go to Checkout</a>
								</div>

								<div class="single__items">
									<div class="miniproduct">
                                        {% for item in basket %}


                                            <div class="item01 d-flex mt--20">

											<div class="thumb">

												<a>{% if item.book.photo %}
											<a class="first__img" href="{% url 'book_detail' item.book.pk %}"><img src="{{ item.book.photo.url }}" alt="product image" width="80" height="100"></a>
                                            {% else %}
                                            <a class="first__img" href="{% url 'book_detail' item.book.pk %}"><img src="{% static 'images/icon_defal.jpg' %}" alt="product image" width="80" height="100"></a>
                                            {% endif %}</a>
											</div>
											<div class="content">
												<h6><a href="product-details.html">{{ item.book.name }}</a></h6>
												<span class="prize">{{ item.price_prod }}</span>
												<div class="product_prize d-flex justify-content-between">
													<span class="qun">{{item.count_prod}}</span>
													<ul class="d-flex justify-content-end">
														<li><a href="#"><i class="zmdi zmdi-settings"></i></a></li>
														<li><a href="#"><i class="zmdi zmdi-delete"></i></a></li>
													</ul>
												</div>
											</div>
                                                </div>
                                            {% endfor %}
										</div>

									</div>
								</div>

							</div>

						<!-- End Shopping Cart -->
							</li>
							<li class="setting__bar__icon"><a class="setting__active" href="#"></a>
								<div class="searchbar__content setting__block">
									<div class="content-inner">
										<div class="switcher-currency">
											<strong class="label switcher-label">
												<span>Аккуант</span>
											</strong>
                                        {% if user.is_authenticated %}
											<div class="switcher-options">
												<div class="switcher-currency-trigger">
													<div class="setting__menu">
                                                    <span><a href="{% url 'logout' %}">Выйти</a></span>
                                                        <span>{% if user.first_name %}{{ user.first_name }} {{ user.last_name }}{% else %}Пользователь{% endif %}</span>
                                                    </div>
                                                </div>
                                            </div>
                                                    {% else %}
                                                <div class="switcher-options">
												<div class="switcher-currency-trigger">
                                                    <div class="setting__menu">
														<span><a href="{% url 'auth' %}">Войти</a></span>
														<span><a href="{% url 'registration' %}">Регистрация</a></span>
													</div>
												</div>
											</div>
										</div>
                                        {% endif %}
									</div>
								</div>
							</li>
						</ul>
					</div>
				</div>
				<!-- Start Mobile Menu -->
				<div class="row d-none">
					<div class="col-lg-12 d-none">
						<nav class="mobilemenu__nav">
							<ul class="meninmenu">
								<li><a href="index.html">Home</a>
									<ul>
										<li><a href="index.html">Home Style Default</a></li>
										<li><a href="index-2.html">Home Style Two</a></li>
										<li><a href="index-box.html">Home Box Style</a></li>
									</ul>
								</li>
								<li><a href="#">Pages</a>
									<ul>
										<li><a href="about.html">About Page</a></li>
										<li><a href="portfolio.html">Portfolio</a>
											<ul>
												<li><a href="portfolio.html">Portfolio</a></li>
												<li><a href="portfolio-three-column.html">Portfolio 3 Column</a></li>
												<li><a href="portfolio-details.html">Portfolio Details</a></li>
											</ul>
										</li>
										<li><a href="my-account.html">My Account</a></li>
										<li><a href="cart.html">Cart Page</a></li>
										<li><a href="checkout.html">Checkout Page</a></li>
										<li><a href="wishlist.html">Wishlist Page</a></li>
										<li><a href="error404.html">404 Page</a></li>
										<li><a href="faq.html">Faq Page</a></li>
										<li><a href="team.html">Team Page</a></li>
									</ul>
								</li>
								<li><a href="shop-grid.html">Shop</a>
									<ul>
										<li><a href="shop-grid.html">Shop Grid</a></li>
										<li><a href="shop-list.html">Shop List</a></li>
										<li><a href="shop-left-sidebar.html">Shop Left Sidebar</a></li>
										<li><a href="shop-right-sidebar.html">Shop Right Sidebar</a></li>
										<li><a href="shop-no-sidebar.html">Shop No sidebar</a></li>
										<li><a href="single-product.html">Single Product</a></li>
									</ul>
								</li>
								<li><a href="blog.html">Blog</a>
									<ul>
										<li><a href="blog.html">Blog Page</a></li>
										<li><a href="blog-left-sidebar.html">Blog Left Sidebar</a></li>
										<li><a href="blog-no-sidebar.html">Blog No Sidebar</a></li>
										<li><a href="blog-details.html">Blog Details</a></li>
									</ul>
								</li>
								<li><a href="{% url 'contact' %}">Contact</a></li>
							</ul>
						</nav>
					</div>
				</div>
				<!-- End Mobile Menu -->
	            <div class="mobile-menu d-block d-lg-none">
	            </div>
	            <!-- Mobile Menu -->	
			</div>		
		</header>
		<!-- //Header -->
		<!-- Start Search Popup -->
		<div class="brown--color box-search-content search_active block-bg close__top">
			<form id="search_mini_form" class="minisearch" action="#">
				<div class="field__search">
					<input type="text" placeholder="Search entire store here...">
					<div class="action">
						<a href="#"><i class="zmdi zmdi-search"></i></a>
					</div>
				</div>
			</form>
			<div class="close__wrap">
				<span>close</span>
			</div>
		</div>
		<!-- End Search Popup -->
        <!-- Start Slider area -->
        <div class="slider-area brown__nav slider--15 slide__activation slide__arrow01 owl-carousel owl-theme">
        	<!-- Start Single Slide -->
	        <div class="slide animation__style10 bg-image--8 fullscreen align__center--left ">
	            <div class="container">
	            	<div class="row">
	            		<div class="col-lg-12">
	            			<div class="slider__content">
		            			<div class="contentbox">
								    <h3>Boighor_</h3>
		            				<h2>The Best <span>Online</span></h2>
		            				<h2 class="another">book <span>shop </span></h2>
									<p>Boighor specifically created for authors and writes to present and sell their books online Soufflé tart sweet. </p>
				                   	<a class="shopbtn" href="#">shop now</a>
		            			</div>
	            			</div>
	            		</div>
	            	</div>
	            </div>
            </div>
            <!-- End Single Slide -->
        	<!-- Start Single Slide -->
	        <div class="slide animation__style10 bg-image--9 fullscreen align__center--left">
	            <div class="container">
	            	<div class="row">
	            		<div class="col-lg-12">
	            			<div class="slider__content">
		            			<div class="contentbox">
								    <h3>Boighor_</h3>
		            				<h2>The Best <span>Online</span></h2>
		            				<h2 class="another">book <span>shop </span></h2>
									<p>Boighor specifically created for authors and writes to present and sell their books online Soufflé tart sweet. </p>
				                   	<a class="shopbtn" href="#">shop now</a>
		            			</div>
	            			</div>
	            		</div>
	            	</div>
	            </div>
            </div>
            <!-- End Single Slide -->
        </div>
        <!-- End Slider area -->
	

templates/inc/_header_account.html
<!-- Header -->
{% load static %}
<header id="wn__header" class="oth-page header__area header__absolute sticky__header">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-4 col-sm-4 col-7 col-lg-2">
				<div class="logo">
					<a href="index.html">
						<img src="{% static 'css/images/logo/logo.png' %}" alt="logo images">
					</a>
				</div>
			</div>
			<div class="col-lg-8 d-none d-lg-block">
				<nav class="mainmenu__nav">
					<ul class="meninmenu d-flex justify-content-start">
								<li class="drop with--one--item"><a href="{% url 'index' %}">Книги</a></li>
								<li class="drop"><a href="{% url 'authors' %}">Авторы</a></li>
								<li><a href="{% url 'contact' %}">Контакты</a></li>
                                {% if user.is_authenticated and user.is_superuser  %}
                                <li><a href="{% url 'admin:index' %}">Админка</a></li>
                                {% endif %}
                                {% if user.is_authenticated %}
                                    {% if user.groups.all.0.name == 'Администратор' %}
                                <li class="drop"><a href="">Администрирование</a>
                                    <div class="megamenu mega03">
									<ul class="item item03">
										<li><a href="{% url 'supplire_admin' %}">Администрирование поставщиков</a></li>
										<li><a href="{% url 'books_admin' %}">Администрирование книг</a></li>
										<li><a href="{% url 'author_admin' %}">Администрирование авторов</a></li>
									</ul>
                                    </div>
								</li>
                                {% endif %}
                                {% endif %}
                    </ul>
				</nav>
			</div>
			<div class="col-md-8 col-sm-8 col-5 col-lg-2">
				<ul class="header__sidebar__right d-flex justify-content-end align-items-center">
					<li class="shop_search"><a class="search__active" href="#"></a></li>
					<li class="wishlist"><a href="#"></a></li>
					<li class="shopcart"><a class="cartbox_active" href="#"><span class="product_qun">3</span></a>
                    {% if user.is_authenticated %}
                            <li ><a href="#"><span>{% if user.first_name %}{{ user.last_name }} {{ user.first_name }}{% else %}Пользователь{% endif %}</span></a></li>
                            {% endif %}
						<!-- Start Shopping Cart -->
						<div class="block-minicart minicart__active">
							<div class="minicart-content-wrapper">
								<div class="micart__close">
									<span>close</span>
								</div>

								<div class="mini_action checkout">
									<a class="checkout__btn" href="{% url 'list_basket_prod' %}">Go to Checkout</a>
								</div>

								<div class="single__items">
									<div class="miniproduct">
                                        {% for item in basket %}


                                            <div class="item01 d-flex mt--20">

											<div class="thumb">

												<a>{% if item.book.photo %}
											<a class="first__img" href="{% url 'book_detail' item.book.pk %}"><img src="{{ item.book.photo.url }}" alt="product image" width="80" height="100"></a>
                                            {% else %}
                                            <a class="first__img" href="{% url 'book_detail' item.book.pk %}"><img src="{% static 'images/icon_defal.jpg' %}" alt="product image" width="80" height="100"></a>
                                            {% endif %}</a>
											</div>
											<div class="content">
												<h6><a href="product-details.html">{{ item.book.name }}</a></h6>
												<span class="prize">{{ item.price_prod }}</span>
												<div class="product_prize d-flex justify-content-between">
													<span class="qun">{{item.count_prod}}</span>
													<ul class="d-flex justify-content-end">
														<li><a href="#"><i class="zmdi zmdi-settings"></i></a></li>
														<li><a href="#"><i class="zmdi zmdi-delete"></i></a></li>
													</ul>
												</div>
											</div>
                                                </div>
                                            {% endfor %}
										</div>

									</div>
								</div>

							</div>

						<!-- End Shopping Cart -->
<li class="setting__bar__icon"><a class="setting__active" href="#"></a>
								<div class="searchbar__content setting__block">
									<div class="content-inner">
										<div class="switcher-currency">
											<strong class="label switcher-label">
												<span>Аккуант</span>
											</strong>
                                        {% if user.is_authenticated %}
											<div class="switcher-options">
												<div class="switcher-currency-trigger">
													<div class="setting__menu">
                                                    <span><a href="{% url 'logout' %}">Выйти</a></span>
                                                        <span>{% if user.first_name %}{{ user.last_name }} {{ user.first_name }}{% else %}Пользователь{% endif %}</span>
                                                    </div>
                                                </div>
                                            </div>
                                                    {% else %}
                                                <div class="switcher-options">
												<div class="switcher-currency-trigger">
                                                    <div class="setting__menu">
														<span><a href="{% url 'auth' %}">Войти</a></span>
														<span><a href="{% url 'registration' %}">Регистрация</a></span>
													</div>
												</div>
											</div>
										</div>
                                        {% endif %}
									</div>
								</div>
							</li>
				</ul>
			</div>
		</div>
		<!-- Start Mobile Menu -->
		<div class="row d-none">
			<div class="col-lg-12 d-none">
				<nav class="mobilemenu__nav">
					<ul class="meninmenu">
						<li><a href="index.html">Home</a>
							<ul>
								<li><a href="index.html">Home Style Default</a></li>
								<li><a href="index-2.html">Home Style Two</a></li>
								<li><a href="index-box.html">Home Box Style</a></li>
							</ul>
						</li>
						<li><a href="#">Pages</a>
							<ul>
								<li><a href="about.html">About Page</a></li>
								<li><a href="portfolio.html">Portfolio</a>
									<ul>
										<li><a href="portfolio.html">Portfolio</a></li>
										<li><a href="portfolio-three-column.html">Portfolio 3 Column</a></li>
										<li><a href="portfolio-details.html">Portfolio Details</a></li>
									</ul>
								</li>
								<li><a href="my-account.html">My Account</a></li>
								<li><a href="cart.html">Cart Page</a></li>
								<li><a href="checkout.html">Checkout Page</a></li>
								<li><a href="wishlist.html">Wishlist Page</a></li>
								<li><a href="error404.html">404 Page</a></li>
								<li><a href="faq.html">Faq Page</a></li>
								<li><a href="team.html">Team Page</a></li>
							</ul>
						</li>
						<li><a href="shop-grid.html">Shop</a>
							<ul>
								<li><a href="shop-grid.html">Shop Grid</a></li>
								<li><a href="shop-list.html">Shop List</a></li>
								<li><a href="shop-left-sidebar.html">Shop Left Sidebar</a></li>
								<li><a href="shop-right-sidebar.html">Shop Right Sidebar</a></li>
								<li><a href="shop-no-sidebar.html">Shop No sidebar</a></li>
								<li><a href="single-product.html">Single Product</a></li>
							</ul>
						</li>
						<li><a href="blog.html">Blog</a>
							<ul>
								<li><a href="blog.html">Blog Page</a></li>
								<li><a href="blog-left-sidebar.html">Blog Left Sidebar</a></li>
								<li><a href="blog-no-sidebar.html">Blog No Sidebar</a></li>
								<li><a href="blog-details.html">Blog Details</a></li>
							</ul>
						</li>
						<li><a href="contact.html">Contact</a></li>
					</ul>
				</nav>
			</div>
		</div>
		<!-- End Mobile Menu -->
		<div class="mobile-menu d-block d-lg-none">
		</div>
		<!-- Mobile Menu -->
	</div>
</header>
<!-- //Header -->
<!-- Start Search Popup -->
<div class="box-search-content search_active block-bg close__top">
	<form id="search_mini_form" class="minisearch" action="#">
		<div class="field__search">
			<input type="text" placeholder="Search entire store here...">
			<div class="action">
				<a href="#"><i class="zmdi zmdi-search"></i></a>
			</div>
		</div>
	</form>
	<div class="close__wrap">
		<span>close</span>
	</div>
</div>
<!-- End Search Popup -->
<!-- Start Bradcaump area -->
<div class="ht__bradcaump__area bg-image--6">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="bradcaump__inner text-center">
					<h2 class="bradcaump-title">{{ title }}</h2>
					<nav class="bradcaump-content">
						<a class="breadcrumb_item" href="{% url 'index' %}">Home</a>
						<span class="brd-separetor">/</span>
						<span class="breadcrumb_item active">{{ title }}</span>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Bradcaump area -->